### ISSUE TITLE
Two notifications for one user rating

### ISSUE THREAD

**Issue by LucasDelvallet** [gamejolt/issue-tracker#1083]
When a user rate any of my game, sometimes, the notification appears twice at the same moment. And the rating has been counted only once, which is normal.

If you want an example, one of my game, Eburnean, has two 3/5 ratings in total, but, in my feed, I have three 3/5 ratings. Because, one time, the notification appeared twice :

![rates](https://user-images.githubusercontent.com/10408678/34638168-7bdda69e-f2c6-11e7-926e-92df92934fd4.PNG)
![1 3](https://user-images.githubusercontent.com/10408678/34638169-7f11d2ae-f2c6-11e7-85d4-9f48230ed625.PNG)
![2 3](https://user-images.githubusercontent.com/10408678/34638171-80db3684-f2c6-11e7-9943-8c5ee98431cc.PNG)

It happened to me several times. And to other user too :  https://gamejolt.com/f/troll-ratings-removed-when-found/341829

I hope that I've given enough information 😄

**Comment by Tricky1975** [comment]
This happens when somebody rates, then unrates and then rates again.
That's is not against the rules, as this could be result of doubt or sometimes even a malfunctioning of the site or the browser or well anything. The multiple notifications can be pretty confusing, as you'd easily think you're target of a troll-rater. This has happened to me too long before (before I became a mod, as I can now look for myself if I see multiple ratings in such a short time). 
Now if e-mails are sent they cannot be retracted (that's just the downside of e-mail), but notifications on the site, can be, can't they?

**Comment by YLivay** [comment]
Yeah, its a bug if they dont go away when users flick rate stuff - it definitely should.

**Comment by hworld** [comment]
@YLivay we fixed this yeah?

**Comment by YLivay** [comment]
yup
