### ISSUE TITLE
Windows Downloader

### ISSUE THREAD

**Issue by EPICMINIMAN64** [gamejolt/issue-tracker#1119]
every time I try to download the game client for windows it always gets blocked by windows defender and I had to download to other two.can you fix the security for it so I can download the client?

**Comment by qwertychouskie** [comment]
That's a problem with Windows Defender, not gamejolt.  Please report it as a false positive.

**Comment by Tricky1975** [comment]
Windows Defender would have a serious issue if the folks of Game Jolt could "fix" this, because, if we can, everybody can, and malware coders would have a little party, as it would render Defender completely useless. After all the client installs software Defender doesn't know and thus it's blocking nature to "protect you" (without actually scanning the file). Indeed you should be able to configure Defender to accept these files. 
Virus Scanners often block any file from a source the Virus Scanner Devs are not familiar with. 

I'd love to show you how you can set Defender right or how to mark things as a "false positive" like @qwertychouskie says, but unfortunately, as a mac-user, I don't have Windows Defender... :(

**Comment by acemod13** [comment]
I have reported the client as false positive. It seems that SmartScreen doesn't report it as possible malware anymore.

**Comment by EPICMINIMAN64** [comment]
ok thanks

**Comment by YLivay** [comment]
this has been giving us a lot of trouble for a while now. we're STILL looking into making this work better, but contacting Microsoft to figure out why it even gets flagged yielded no results yet S:
