### ISSUE TITLE
New features never appear in Client?

### ISSUE THREAD

**Issue by Dragonify** [gamejolt/issue-tracker#1130]
Ok I'm not sure if it happens only at mine or I'm just stupid for not knowing the reason, but is this normal? I can't use Dark Mode and theme color in Client.

**Comment by hworld** [comment]
It's a pain that Client hasn't been updating as fast as the web site has. We're working on fixing it. The reason we couldn't push out dark mode and themes for Client yet is because the Chrome wrapper we're using (nwjs) is using a really outdated version of Chrome that doesn't support CSS variables. Our update process currently only supports updating the Client application files and not the whole wrapper as well. We're working on a new updater that will support full update flows right now. It'll allow us to update Client just as often as we update the site with all the new features right as they happen.

We expect to get it out some time this week. 

Here is the frontend branch for this work: https://github.com/gamejolt/gamejolt/pull/189
And here is the branch for the updater work: https://github.com/gamejolt/joltron/pull/3

You can follow along as we work on it if you're super nerdy. =]

**Comment by Dragonify** [comment]
Totally understand! Thanks for the response. And while you guys are doing the update, please get some rest :)

**Comment by YLivay** [comment]
> We expect to get it out some time this week.
Oh boy, im experiencing some sharp internal pain revisiting this issue.
Just updating - we're still working on it, had to take a few detours but its coming along.

**Comment by Dragonify** [comment]
Oh hey! Ha, yeah it's been a long time since this post. That time I was like "Hmm, still hasn't update the thing yet? Welp, everything needs time." But hey, totally understandable, I'm a guy who is cool with everything. Only one question: Do you actually have a expected time to release it this time? It's not like this update is SUPER important, just curious.
