### ISSUE TITLE
Unable to open client

### ISSUE THREAD

**Issue by khawar1024** [gamejolt/issue-tracker#1171]
I can't download game jolt new update
when I download game jolt it says unable to execute the file in the temporary directory. setup aborted.
Error 5: access is denied

**Comment by YLivay** [comment]
Hey, where exactly do you see this error message? Are you on Windows? How did you download the update? through https://gamejolt.com/client or somewhere else?

**Comment by niksudan** [comment]
This is a Windows error. According to [this article](https://ugetfix.com/ask/how-to-fix-unable-to-execute-files-in-the-temporary-directory-setup-aborted-error-5-access-is-denied-on-windows/), @khawar1024 is trying to install it to a directory they don't have permission for.

Try right-clicking the installer and select "Run as Administrator", if available.

**Comment by YLivay** [comment]
Thanks @niksudan , just adding to the answer - the client is perfectly capable of running without any administrative rights as long as you install it to a location you have permissions to.

By default we install to `%LOCALAPPDATA%` which every user has full read/write access to. If the installer does not ask you to pick a location its because it detected you already have the client installed elsewhere on the system and would attempt to install in the same location. You can uninstall the old client if you wish to reinstall it to a different location. Don't worry, your games won't be affected :)

I'm closing the issue for now, if there are any other issues let us know!

**Comment by akidmeme** [comment]
I can't open or delete the app
it will say when uninstalling and it says can't delete because it running it I'm not using it
