### ISSUE TITLE
No Longer Can Play Or Download Game Jolt Game On The Client!

### ISSUE THREAD

**Issue by quackquackk** [gamejolt/issue-tracker#1174]
**How are you using Game Jolt?**

Well... I've Been Playing On It For A Few Months Now...

**Please describe the issue you are having**

I No Longer Have The Ability To Download Or Play. There's ALWAYS A Problem No Matter What I Do. I Closed It With The Task Manager... Nothing Happened. So Yeah, You Need To Fix The Client. =)

**Comment by quackquackk** [comment]
> Right after trying to install a game, scroll down to the footer and hit the "Send system report" button. Maybe we'll see what the issue is from there.

Can It Also See What The Problem Is With My Games Not Playing?

**Comment by YLivay** [comment]
Yes, I see what the issue is. For some reason the executable in charge of managing games is missing from your system. This is probably due to a hyper active anti virus quarantining it. Sadly theres nothing we can do about people's anti virus being over protective :(

Try reinstalling the client and setting an exception in your AV and it should be good to go. Don't worry, your games wont be deleted when you reinstall the client and it'll detect them for you again.
