### ISSUE TITLE
Add ability to specify a custom game release date

### ISSUE THREAD

**Issue by NALGames** [gamejolt/issue-tracker#127]
I'd love the ability to add a custom release date on a game. The main use I'd see of this would be to fill out my game library on GameJolt - I'd like to have a GameJolt link for old games I made in years like 2006-2008 without them showing up in Newly Added Games, making people play them thinking I did something shiny and new and ending up thinking I'd released something poor.

Would be nice if, on the profile page, they showed up chronologically as well, so older games were towards the bottom.

**Comment by acidpoison** [comment]
Why not just leave a date in the description?

**Comment by NALGames** [comment]
As said I'd rather it didn't appear, outside of the description, to be a brand spanking new game. It'd be nice to fill out my "game-ography" and have all the dates for game releases appear correctly and in order.

**Comment by hworld** [comment]
Yeah, we've thrown around this idea for a while. I definitely want to get it in place for when the new site launches. Some things I'm worried about are that people would do what they do for jams and set ridiculous dates just to screw with the site.

Might have to make it so that there's a lower "sane" limit to the date. And of course only allowing to set in the past.

**Comment by hworld** [comment]
Oh yeah, and one thing I want to do is separate out the idea of the **release** date and the **posted** date. This way you can still view games recently posted/added to the site so you don't miss things. But also a way to view by release date in case you're only interested in freshly released/new to the world games.

Also, perhaps a silly little thing I added, but if you click on the date that a game as added to the site it allows you to view all games added on that date sorted by their voltage scores: http://wttf.gamejolt.com/games/by-date/2015-02-25

**Comment by Tricky1975** [comment]
"Oh yeah, and one thing I want to do is separate out the idea of the release date and the posted date. This way you can still view games recently posted/added to the site so you don't miss things."
I think this is a good idea, otherwise I fear this feature will be abused. I think we do need the mods to see how often the date is changed, so they can take action, or I fear people will keep on updating the release date in order to keep their games high in the "recently added" section. 

Perhaps adding a field for a "release ETA" can be a good thing for games flagged as "in development".

**Comment by hworld** [comment]
I would only allow to set to a date in the past. And if it's changeable it should probably only be allowed to be set _before_ the date that it's already set as.

**Comment by hworld** [comment]
Oh, and the release ETA is definitely a planned feature for in-dev games. That'll happen when we do the planned changes to the in-dev games section, though. More info on that in the future.

**Comment by NALGames** [comment]
For repeated editing, I'd suggest that only being able to set it once (or maybe twice just to account for input error) would be fine, after which it's locked. And I totally agree on an ETA system replacing the release date system for WIPs.

I'm also fine with release date and posted date being separated. However, I still think it'd be nice to have the option for a game to bypass the "New Games" section (maybe only if the release date of the game is in the past) - there's no real benefit to someone doing this apart from not drawing attention to something older.

**Comment by niksudan** [comment]
This has been migrated to the gj-improve forum.

https://gamejolt.com/f/custom-release-dates/341364
