### ISSUE TITLE
Unity Web games are listed as HTML games

### ISSUE THREAD

**Issue by variousauthors** [gamejolt/issue-tracker#160]
When searching for games, the browser category of filters include "HTML" and "UNITY". What I've noticed is that the distinction here is arbitrary: sometimes a unity web player game will show up as [Unity and not HTML][0], sometimes [as HTML and not Unity][1]. For many users, this will not be a cause for concern because they will have both HTML and UNITY selected. The fact is that unity web player is a plugin, and it isn't available to linux users.

Aside: I've heard talk that Unity is working on a native client for Google Chrome or something? Something that would work on Linux. I'm not sure if that shipped with Unity 5 or not, but regardless, existing unity web player games won't work on Linux but still show up in filtered searches like +Linux +HTML -Unity

[0]: http://wttf.gamejolt.com/games/green-to-red-v-1-00/53395
[1]: http://wttf.gamejolt.com/games/winning-streak/38661

**Comment by banreaxe** [comment]
The Unity Plugin is basically dead now, due to chrome not allowing native plugins anymore. There was a chrome native client plugin, but that is now obsolete.

So now unity has an option to export games to HTML5, its been out for awhile but has recently become a full version and is out of beta/testing phase.

In short, some Unity games are HTML5 now.

**Comment by YLivay** [comment]
Yup, it's exactly what it is. The distinction is necessary tho.
