### ISSUE TITLE
Scroll wheel button bug

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#191]
I was scrolling down the site with the scroll wheel button but after I stop clicking the wheel the cursor didn't change to the default one and everything became unclickable

![gjnesttest](https://cloud.githubusercontent.com/assets/11754980/6942161/560e5ae4-d88e-11e4-9e4f-6a8e63354a01.gif)

 I hope I explained the bug well, I suck at explaining things

**Comment by NickRock** [comment]
Edit:
This was on chrome

**Comment by acidpoison** [comment]
Yup, happened to me too. I tried to middle click a link during chat and this happened.

**Comment by orcolom** [comment]
going to a different part of gamejolt using url, keep this broken.

on my side only happpens on a page were a add is shown. (needs more people to clearefy)

**Comment by acidpoison** [comment]
Alright, I found out one way to get this to happen, or at least some version of it. Fully replicable, too.

Go to the homescreen, and middle click a dot on the featured slideshow. the cursor will turn into the wheel-scroll icon. When you move it around, it will switch to a finger cursor and everything will become unclickable.

I'm not sure if this has anything to do with what is happening in the bugs above, but the effects are similar, so I am guessing that they are related in some way.

**Comment by acidpoison** [comment]
Found a way to replicate it, at least for me.

Go to the WTTF homepage and middle click a dot on the featured slideshow. Move the cursor around the screen quickly and it should become locked onto one cursor and cause the bug.

Reloading the page doesn't fix it, neither does switching to a different WTTF page. In order to fix it, you need to go to a non-WTTF page, then re-open WTTF.

I asked @Agrosis to test it, but he said it doesn't happen for him. It could be specific to some computers or versions of Chrome.

**Comment by hworld** [comment]
Is this fixed now?

**Comment by acidpoison** [comment]
As far as I can tell, it's fixed.

**Comment by NickRock** [comment]
It didn't happen to me again

**Comment by hworld** [comment]
So, I think this was related to really old styles where we had the panes on left and right. In that case the middle content had to be its own scroll area. I was able to get rid of this hackiness when we got rid of the left/right pane. Should be fixed.

**Comment by Fappp** [comment]
Trying to use mouse wheel click on the chat to scroll up hangs the entire client, might need to be reopened. Win7 x64
