### ISSUE TITLE
Pagination for scoreboards.

### ISSUE THREAD

**Issue by hworld** [gamejolt/issue-tracker#28]
Right now you can't view more than the top 100 scores.

**Comment by jahndis** [comment]
I'm actually experiencing an issue where I can only view the top 3 scores for one of my games (both in the management view and in the main game page view). For another game I can only see the top 25 in the management view. I'd love to be able to see the others :) This seems more like a bug.

If you're interested in seeing which games I'm having problems with:
http://gamejolt.com/games/swing-time/66095 (only top 3 scores are shown)
http://gamejolt.com/games/the-loudest-ballerina/27569 (only top 25 scores are shown)

**Comment by YLivay** [comment]
Hey @jahndis, can you only see 3 scores in the developer dashboard for that game? Ir in the game page? Can you describe what were you expecting to see? Also, if unique scoring is on can you try disabling it and checking again?

**Comment by jahndis** [comment]
I can only see 3 scores in both views. To be clear, I can see the top 3 scores on the game page, and then a few of the most recently submitted scores are shown below (via AJAX I assume). I can only see three scores in the developer view. I'd expect to see all 700+ scores in the developer view, and at least a few more than three on the game page, but maybe that's not the case? 

I tried disabling and checking unique scores, and I think I might see the problem. Alright, so with unique scores, I only see 3 "users" right? Two are gamejolt user scores and one is a guest score. When I uncheck unique scores, I can see (most of) the submitted scores. It turns out in the top 25 (which appear to be all that are shown on the game page), there are only three "users" that appear (the users that were originally only shown with one score each).

What I DO think is a bug is the fact that, since the top 25 scores mostly consist of one player's scores, it is knocking off other gamejolt user's scores from the top 25 even though the scores are supposed to be unique. For example, there is a score from a gamejolt user at rank 35 that would easily be 4th on the leader board if all of the scores from the user with rank 1 weren't knocking it off. My guess is some code is only getting the top 25 scores, and then "uniqueifying" them rather than pulling all the scores, "uniquifying" them, and then taking the top 25 from that set. That's just a guess.

**Comment by YLivay** [comment]
Hey, thats my guess too - checking :)
