### ISSUE TITLE
Accept all/decline all buttons to friend request window

### ISSUE THREAD

**Issue by Savordez** [gamejolt/issue-tracker#282]
Not a major thing, but I'd like to see this implemented. Probably wouldn't be all that useful to regular gamer joes but a swood thing for devs who keep getting friend requests. o_o

**Comment by hworld** [comment]
Interesting. Would a setting that says people can't friend request help out at all? The only problem is that if two people say "can't friend me" they'll never be able to friend each other.

**Comment by YLivay** [comment]
Maybe a setting for "dont show me friend requests" rather than not being able to receive. and if two people request each other it'll make them friends anyways. This way when you toggle off the feature you can auto decline whatever friend requests you've received that are unanswered, possibly with a confirmation dialog so you can choose to maybe review these requests after all.

**Comment by Savordez** [comment]
I actually meant something like a button that accepts/declines every current friend request instead of doing it one by one, but the "don't show me friend requests" setting sounds pretty neat too.

**Comment by Tricky1975** [comment]
Hard for me to check as I don't have any open incoming friend requests right now, but is this one already implemented or should it be moved to gj-improve?
