### ISSUE TITLE
Can't set launch options for linux/mac build

### ISSUE THREAD

**Issue by jahndis** [gamejolt/issue-tracker#311]
I was creating a build for Linux and Linux 64 bit systems, and I uploaded a zip file. GameJolt informed me that it didn't know how to auto-run the build, so I typed in the path to the executable. When I pressed "Set Launch Options", I got a 500 Internal Server Error.

The web console shows:

    Failed to load resource: the server responded with a status of 500 (Internal Server Error)

    POST https://gamejolt.com/site-api/web/dash/developer/games/builds/launch-options/set/66095/154368/178255/216627 500 (Internal Server Error)

This is in Chrome on Linux 64bit.
The zip file extracts to (with changed names):

    - gamename
      - libs...
      - executable
      - otherlibs...

And the path I entered for the launch options was "executable". I don't know if this is the proper way to do it. I have not tried this on other OS's or browsers yet.

**Comment by jahndis** [comment]
I also had the chance to try this out on mac as well. I'm getting the same 500 Internal Server Error when I try to set the Launch Options for Mac and Mac 64 builds.

**Comment by raeleus** [comment]
Hey! I have a related issue [here](https://github.com/gamejolt/issue-tracker/issues/313). Basically what I've come to find out through experimentation is that the Game Jolt uploader is trying to find what it thinks to be an executable for each platform when you upload an archive file of any kind. Specifically a file with an extension .exe for windows and .sh for Linux. Mac is a tad bit more involved: a folder path as follows "gamename.app/Contents/" with files PkgInfo and Info.plist
I have to imagine that you don't use these files at all to launch your game on Linux or Mac. The workaround is to create blank text files and rename them to the above specs and insert them into your zip. I tested this and it works for my case. This is not ideal at all and will probably confuse the heck out of your users.
Another workaround is to upload your zip as an "Other" distribution. This is an even worse option because your game will no longer come up as Linux or Mac compatible, however Game Jolt won't accost you for an executable path.
I think the idea behind this feature is for GameJolt to support QuickPlay as a default option now or in the future. I can't say for certain because I don't see a possible way for that to ever work under Linux at least. Browsers aren't going to support anything like that anymore in the near future as far as I have been able to research either.

**Comment by Tricky1975** [comment]
In earlier games of mine "quick play" wouldn't even work (the games on which I tried all appeared to crash), so I actually stopped giving any support for this. Obliging me to set up such options, and thus forcing me to give any support for this, is for me the same as obliging me to stop releasing my games on GameJolt and strictly host them elsewhere. And indeed, since Java actually appears to block features as these, and also since most OSes are about to block any programs run in the way "Quick Play" works (and this time for understandable reasons since this is also the way malware works).

On Mac you can best leave the "mygame.app/contents/macos/mygame" file (which is the true executable) the way it is and just consider the folder "mygame.app" itself as the executable file. Mac users will all expect that (a lot of them don't even know that the .app bundles are not files but folders), and languages that set the executable path default as the executable path (like BlitzMax) will only do so properly if the .app folder itself as regarded as the executable. 

If this is for a GameJolt client (like Steam or the Apple App Store), I'm more game to get this show on the road, however a full support on how each OS calls its executable files/folders then then desirable.

**Comment by hworld** [comment]
@Tricky1975 This is for the Game Jolt Client that is coming soon. This has nothing to do with Quick Play. Quick Play is removed. We work really hard to detect the launch options automatically now. WAY better than we ever did before. Is it not working for your games, or have you not tried yet? If you go into your current games and click into Builds & Files you should be able to see what launch options we detected.

@jahndis Is there any way you can upload it to dropbox and send us a link to test? It's really hard to know what you're attempting to upload without seeing it. Also, doing `.sh` for your filename shouldn't matter. For mac/linux it will pull from extension-less filenames as well. Also, when setting your launch options there should be a [...] button that you can click to see a list of all the files we think are selectable for the platform you chose. Does that show anything?

**Comment by Tricky1975** [comment]
A client? We're actually getting a client? For Windows, Mac AND Linux? If so that would be great news for all of us ;)
I've not yet fully tried, as that would spook up my current games. I do have a "fake game" to test things out further, and I was about to try this out, but my schedule didn't allow me to. I was only a bit worried about what I read and I expressed those worries and I wanted to make sure things were alright and that I wouldn't be forced into a system that I have bad experiences with. Apologies if I sounded a bit too harsh on this.

**Comment by hworld** [comment]
Yeah, it's the main reason for the changes with builds. To have separate installable packages that are versioned so they can be auto-updated, and tagged correctly for the platform they work on, with a description of how they are launchable.

Here's a quick tweet I did showing some progress of the client. It's mainly the site with added game management functionality. It's already working in a very barebones state. I run Linux, so this is it running on a Linux machine: https://twitter.com/gamejolt/status/614934824734838784

**Comment by Tricky1975** [comment]
Cool. :) :+1:

**Comment by YLivay** [comment]
So is this an actual issue?

**Comment by jahndis** [comment]
Sorry for the delay. Here is a link to the zip file I uploaded from linux:

https://www.dropbox.com/s/dyodh8hh4i5cyiy/swingtime.zip?dl=0

I am currently getting no launch options when I click on the [...] button to right of the Linux and Linux 64bit launch options text inputs. So I assume it's not detecting my executable file correctly. I'll upload the mac build I tried to use in a moment.

**Comment by jahndis** [comment]
Here is the mac build:

https://www.dropbox.com/s/20r5tmglpaljv88/swingtime_mac.zip?dl=0

Similarly, I see no launch options for mac or mac64 when I click the [...] button to the right of the launch option text input.

**Comment by jahndis** [comment]
@YLivay I still would consider this an issue, as I currently cannot create valid builds for mac or linux versions of my game (although I still would like to try the workarounds described above). Let me know if you need any more information from me to fix this.

**Comment by Tricky1975** [comment]
My mail client would have loved you if you put all that in one post :)
I believe the Linux builds are supposed to react on an .sh file which starts the executable.
On Mac we have the bundle structure in which the folder in which the app is located (always suffixed as .app) is considered by OS X as the executable. Opening this folder in the finder will start the application in it. Is this bundle structure completely taken into account (as this means that in the Mac Builds the launch "file" is actually the application folder itself. You don't want to direct directly to the binary file. Mac programs are known to act very crazily if you do that).

**Comment by jahndis** [comment]
Sorry about that. Just noticed the edit button :)

**Linux**
I was successfully able to upload a zip file! Before, I had the game executable and all necessary libs/assets in a folder called <gamename>, which I then added to <gamename>.zip. For whatever reason GameJolt wasn't picking this up.

Now I tried selecting all of the game files (executable, libs, assets) and adding those to <gamename.zip>, which put the executable file in the first level of the archive. This seemed to please the almighty GameJolt ;). Note that I did NOT need to have the ".sh" extension on the executable.

This might still be a bug, because typically I get frustrated when someone who zips just their game files rather than put their game in a directory and then zip that directory. The reason is that when you unzip the file, it dumps all of the libs, README's and etc. into the current directory (bleh), whereas if the game contents were put into a directory before zipped, it all gets extracted to that one directory (nice), making it a bit cleaner to work with. (Yes I know I can specify an output directory when unzipping, but I still think the other way should be supported as it's quite common).

**Mac**
I tried just uploading the application folder ([gamename].app), but for whatever reason, GameJolt is renaming the archive to [gamename].app.zip, and then indicates it doesn't know how to auto-run, and doesn't show anything in the launch options file browser, and gives an internal error when manually specifying launch options (which is still a bug). For what it's worth, the [gamename].app folder structure looks like this:

    [gamename].app
        - Contents
            - MacOS -> Contains libs and actual executable
            - Resources -> Contains assets
            - Entitlements.plist
            - Info.plist

My guess is the problem has to do with the renaming of the app folder on upload?

**Comment by hworld** [comment]
@Tricky1975 For mac, the `.app` folder is correctly detected as the executable path.

I'll have Yariv continue looking into this to see what's up with the oddness.

**Comment by Tricky1975** [comment]
Cool. Forgive me, I had to check, I did deal in the past with people who never knew how a Mac .app bundle works, so I just had to make 100% sure.

**Comment by wongcito** [comment]
Hello, I'm having the same problem. I uploaded a zip file with an exe file in the root and the system is still asking me for launch options. What exactly do I have to put there? Thanks a lot.

**Comment by jahndis** [comment]
Why was this closed?

**Comment by Tricky1975** [comment]
Maybe it's fixed.... :-/

**Comment by hworld** [comment]
Oh, sorry, it autoclosed once we pushed out the fix.
It should be fixed. I tested with your two files and it correctly autodetects the files now.

@wongcito Do you still have issues?

**Comment by wongcito** [comment]
No, it was fixed, just needed to have the .exe file on the root of the .zip.
Thanks a lot.

**Comment by hworld** [comment]
Sweet! Gonna keep this closed, then.

**Comment by jahndis** [comment]
Whoops sorry, for some reason the commit was 404ing so I didn't think a commit was associated with the fix. It works! I just tested. Thanks so much for fixing this!
