### ISSUE TITLE
Games Cannot Be Sorted from Dashboard

### ISSUE THREAD

**Issue by banreaxe** [gamejolt/issue-tracker#328]
It seems there is no way for a developer to choose the sorting order of their own games from their dashboard. When you view the developers profile, games are listed in the order they were added and that's that.

As a developer I think we should be to choose the sort order, either by name, rating, views, date etc, either ascending or descending. I also think there should be an option to allow a manual sorting order.

**Comment by hworld** [comment]
It's a little tricky since they're now collections/playlists that people can add into their Library. As such, it follows the default rules of collections. Basically, in the future, it will allow multiple sorting options that the user can choose since it's in their own library.

**Comment by Tricky1975** [comment]
I don’t wanna be a pain in the ass, but… 
I do need this feature once my current game is finished…
I have a few delayed projects already having a game page (hidden at this moment), and I would hate to delete those only to create a brand new game page with the same data only because the order would otherwise work confusing on me (and my “fans”).

Are there any plans about this feature?
