### ISSUE TITLE
Following and unfollowing Forum Topics not possible

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#332]
Though the forum is still under update, the **Follow Topic**-button is currently not working.
When clicking on it and refreshing the page the *marking* is gone and you won't get notifications.

**Firefox 39.0**
**IE 11.0.19**

**Comment by Tricky1975** [comment]
I tried this in Opera (on Mac) and when I click the follow button, the thread will be marked as "followed", but when I leave the thread and come back, the follow seems to be undone. Seeing as this does now affect three big browsers, I guess it's a general issue.

**Comment by indiegamehunt** [comment]
It has also been reported that unfollowing forum topics does not actually unfollow.

**Comment by YLivay** [comment]
Is this still an issue?

**Comment by Tricky1975** [comment]
Yes

**Comment by Tricky1975** [comment]
This issue is becoming more and more annoying.
I receive tons of notifications about stuff happening on the forum, which is not interesting for me, since I visit those multiple times a day, but since I cannot unfollow threads, these notifications keep on coming.

I can understand that forum bugs have low priority since the forums are about to be replaced anyway, but this bug is getting so annoying, that regardless of the situation fix on short term is really required. 

[And I can tell you that it's getting clear I'm not the only one heavily annoyed by the current situation](http://gamejolt.com/community/forums/topics/annoying-things/5960?forum_topic_post_page=76#post-69491).

**Comment by NikSudan** [comment]
Following and unfollowing topics are going to be completely rewritten in the new update. The old forum isn't going to be touched. All I can say is be patient! It'll come soon... I hope!

**Comment by Tricky1975** [comment]
May I request to have all topics I'm following now "unfollowed" though?
The amount of notifications I don't need is killing me.
