### ISSUE TITLE
Notification category "New Comments" deems me "not connected to the internet" while I clearly am!

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#388]
![image](https://cloud.githubusercontent.com/assets/11202073/11451826/8d5196da-95d3-11e5-89db-1f6fc9c68113.png)

I only get this when I try "New Comments". I don't get this message on the other categories, plus all other websites appear to work the way they should (I wouldn't have been able to post this issue if this wasn't the case) :sunglasses:

**Comment by hworld** [comment]
Hmm, this new warning message is part of the work for client, since they may very well be offline. It has to do this work a bit weird, where it tries to detect if a request failed for a "strange" reason, and if so, it assumes it was a connection error. Sadly we don't get much more info than that.

Does the page work? I'm thinking that maybe there is a bug with comments and notifications where it's not showing your notifications correctly and dying on the server through a weird way and therefore returning an invalid response.

**Comment by Tricky1975** [comment]
I'd like to bring [this forum thread](gamejolt.com/community/forums/topics/uploading-build-errors-out/14271) under your attention, though this thread does not handle the notifications section but uploading an HTML5 game, it does result into the same trouble, and I think very likely caused by the same bug. 

I already recommended this guy to contact you over e-mail, but I noted this in this issue as I do believe the trouble is related.

**Comment by hworld** [comment]
This should be fixed in site. Client will get updated as well.
Basically, I changed the logic around a lot so that it happens less often and only when it REALLY thinks you're offline. 
Mostly done in this commit: https://github.com/gamejolt/frontend-lib/commit/93c701a4631e18a6ac68f635b93b76b3ee3c32f0
