### ISSUE TITLE
Feature Request: Add previously installed games to the client

### ISSUE THREAD

**Issue by Cash120** [gamejolt/issue-tracker#421]
It would be nice to be able to add gamejolt games that we've already downloaded to the client without losing all progress in the game.

**Comment by Tricky1975** [comment]
When it comes to "losing progress in the game" it will actually depend on how well the dev of the game created that game. When it comes to ALL my own games for example, if you downloaded them before, then all you got to do is to re-download them through the client and the games should be able to read ALL the data you saved before with the non-client install, simply because I followed the rules the OS set up for me on this department (even when you delete the non-client installation from your system, and that works on my games as well in Windows as on Mac, and the few games that do support Linux have the same thing working). Setting this up well, is actually the responsibility of the game's developer and not of GameJolt.

If you are dealing with a game that does not cover this well, perhaps you should contact that game's developer.

**Comment by Cash120** [comment]
Thanks for the reply; is there a way to integrate game progress for a game that wasn't installed, but instead a zip file?

**Comment by Tricky1975** [comment]
That basically depends on the way the game was developed. And most of all how the data the game creates to save all progress works. And also where it saves this data. And this lies in either in the hands of the dev himself or in the hands of the game creation tool used. That is not something the GameJolt can control.

Now a feature to run Games through the client not downloaded through the client, could be handy, though. Steam also supports such a feature.

**Comment by Cash120** [comment]
The feature to run non-client games through the client like Steam would be a good idea.
