### ISSUE TITLE
Installation path

### ISSUE THREAD

**Issue by darkvergus** [gamejolt/issue-tracker#430]
Can a installation path both for the client as well as for the games be added?

**Comment by Tricky1975** [comment]
I'm not entirely sure what you mean, but you can change the path to install your games to in the client settings. You can get in those setting by clicking your avatar and you'll find it in the menu that pops up.

**Comment by darkvergus** [comment]
i meant installation path for the client itself, since by default its installed in the appdata and i dont install programs in c:

**Comment by Tricky1975** [comment]
You also asked about the games, so I answered that part.
Since you speak of "c:" I guess you are on Windows. Does the windows version come with an installer?
(I'm on mac, and there I can just drag the client to whatever place I want, though /Applications is given in the .dmg file (which is for Mac the standard way of working)).

**Comment by hworld** [comment]
We're not going to do this for now. It increases the friction required to install the client. It's also not possible with our instlaler, so we'd have to change a lot around. And client isn't actually too big, and doesn't really continue to grow in file size like a game lib does.
