### ISSUE TITLE
Downloads are in queued.

### ISSUE THREAD

**Issue by corason2** [gamejolt/issue-tracker#442]
i just downloaded my first game and played it for a while. after quitting the game all my download were in queued and bellow there was and still is this writing "Currently Playing: Bit Pit". Download are still in queued and wont download no matter what i do. i' ve even restarted the computer but nothing happens please fix it in the next update i really like the client version and there are cool games for me to try.

**Comment by Tricky1975** [comment]
The main source of the bug is already reported in #399, making this issue officially a "duplicate".
However, I can help you on one front. I can help you make your downloads running while you are playing a game (for real or because of this bug).

Click on your avatar, at the top right of your screen and choose "client settings" in the menu that pops up.

And then set "Pause when playing" to "No" as demonstrated in the shot below.
![image](https://cloud.githubusercontent.com/assets/11202073/12078457/d0c84484-b213-11e5-9b2c-8efb9fdf1e34.png)

This should at least continue the downloads, and not regard them as "queued".
