### ISSUE TITLE
Uploading a new build is not detecting executables in sub-folders anymore

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#447]
_Uploading a new build is not detecting executables in sub-folders anymore_ when trying to select launch-options, overriding the path does not work either.
This already worked in in the past.

Tested with Windows-32 and Windows-64 build (within same archive).

**Comment by YLivay** [comment]
Are the launch options completely empty when you  try to select a new file? Or just offers wrong results?

**Comment by MausGames** [comment]
I have an archive with an executable at the root (launcher, x86) and two different executables in /bin/windows/x86/ and /bin/windows/x64/.

He now offers me only the launcher in both selection lists - in the past he magically offered me launcher+x86 in the Windows-32 and launcher+x64 in the Windows-64 selection list.

**Comment by YLivay** [comment]
Link the archive you're uploading, i'll look into this!

**Comment by MausGames** [comment]
http://gamejolt.com/games/-/18996/download/build/287722

**Comment by YLivay** [comment]
The issue is because the evaluator doesnt think the executables are a match.
This happens because:
* The executables are 3 level deep
* They are in folders containing many files, making the evaluator think its a dependency/asset/lib type of folder (executables are rarely found directly in those folders)
* It found a better candidate.

Its enough to redefine what is a "big folder" to allow selecting the executables,
though in your specific case I'd actually split the archive into individual ones for each os/arch. This is because users will have to download less and wont download updates that doesnt have to do with their specific version (which in a single archive setup they can't differentiate).

@hworld?

**Comment by YLivay** [comment]
Meh ill just.. put some MORE heuristics in place.
Stop horsing around. Split your archives >:)

**Comment by hworld** [comment]
@YLivay this is probably fixed up, yeah?

**Comment by MausGames** [comment]
Looks fine on my side, though @YLivay should confirm if he is happy with the solution and close the issue.

**Comment by YLivay** [comment]
Yeah, it's been fixed for months, oops!
