### ISSUE TITLE
Support Installers in Client

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#516]
Client should support games that ship as installers.
- [ ] Windows (msi, inno, ~~nsa~~, nsis)
- [ ] Linux (rpm, deb)
- [ ] Mac (dmg)

**Comment by Tricky1975** [comment]
When it comes to mac, supporting dmg is a good start, however,  a lot of .dmg (in the indie/amateur scene most of them) come with a fully ready .app that you can "Drag" to the application folder, however some .dmg files can contain an actual installer (which are just like application bundles directories with a lot of shit inside them, only this time suffixed with ".pkg" in stead of ".app"), are you planning to support BOTH possibilities in the client for Mac? (I'm asking to make sure I have the right approach all the time).

And in Windows .msi is the standard installer format, but some installers (like the ones made with Inno Setup which is one of the most popular free installers) create an .exe file. Of course I cannot expect the client to automatically tell the difference between an .exe file serving as a game or as an installer, but maybe a checkbox for indicating an .exe file is an installer or not could be handy for Windows.

**Comment by YLivay** [comment]
Wish  I could add it to the next version milestone. Gonna probably be done the version after that.

**Comment by luckcolors** [comment]
Well @YLivay as for windows i wouldn't racommend to make the game installers get processd by the client as that isn't going to be guarantited to work 100% (for example inno setup installer are a pain to decompress without installing because thay can get made in a lot of different ways, even encrypted) so my idea for this problem is either:
- 1 Create a gamejolt official setup sdk (even a fork of innosetup or else will work) so then there will be only one standard to support.
- 2 Force the users which want to create a setup to also create an archive of the game which will then be fed to the client.

Also i guess there's another problem on windows which is the redistibuitables:
- 1 Have a "repository" of all the possible windows redists and then have the users apply tags to the required ones on the game archive (so then they will be installed on game install).
- 2 To package them with an install script inside the game archive/setup. (this will then cause a little bit of more heavy installers/archives because the users will have to package them for people which already have them installed.) 
- 3 Leave the end users the task to install them manually.

**Comment by YLivay** [comment]
@luckcolors Good points. The main issue with installers is indeed that we're going to have a harder time getting the valid launch options after the game's installed. Auto detecting it would be nearly impossible with some installers, we're aware, so we might have to make the users get more involved with the extra settings when they choose to upload an installer and it'll be their responsibility to make sure it runs. Gamers will be able to flag games that misbehave and they will be removed.

As for redistributables, that is a headache of its own and out of scope for the installers. The redistributabless are issues to all game forms, not just installers. For example RTP for RPG Maker games or some libs Game Maker: Studio expects you to supply yourself. We'll probably have an index of most commonly used redistributables and add to it as we go based on user input :)

**Comment by Tricky1975** [comment]
[copied to gj-improve](https://gamejolt.com/f/support-installers-in-client/341374)
