### ISSUE TITLE
Client is slow for a minute or so when launching

### ISSUE THREAD

**Issue by FattyJoeMan** [gamejolt/issue-tracker#566]
When launching the GJ Client, things such as mouse and keyboard input are extremely delayed. Sometimes taking up to 5 seconds for keyboard input to register into chat and other text boxes.

Clicking buttons and scrolling can also have about a 5 second delay.

This all stops after about a minute, I assume it has something to do with resources still loading in the background.

**Comment by CyberKiller40** [comment]
Possibly a duplicate of #561

**Comment by YLivay** [comment]
I believe @CyberKiller40 is correct, should be fixed in next version :)
Its most likely the update of some of your installed games or the client itself.

If it happens every time you reopen the client or once every 15-30 minutes it might be a game thats stuck in an infinite update loop. Next time this happens can you scroll down to the footer and submit a system report? It'll help us find which game is responsible and fix it.

( I bet its cardinal crusade >:) )

**Comment by FattyJoeMan** [comment]
I've already sent before and after system reports and I don't have any
games installed, so there shouldn't be anything to update.

**Comment by hworld** [comment]
Confirmed this was fixed for fattyjoe
