### ISSUE TITLE
"Oh no! Could not launch game"

### ISSUE THREAD

**Issue by 3Nex** [gamejolt/issue-tracker#590]
"Oh no! Could not launch game" - is the notification I get when I try to launch a game. 

I installed my first game on Gamejolt client on Linux 64-bit, the game is "A Purr Tale", and when I click the Launch button in the client, only the mentioned notification pops up, nothing else happens. 

I added the execute permissions on the file; didn't help. 

I can launch the game by manually navigating to the game's folder and launching the executable file.

**Comment by CyberKiller40** [comment]
This is usually a case of wrong game setup by the games developer. They didn't point to the correct executable file in the build options on the site.

**Comment by YLivay** [comment]
If the file wasnt executable it means it has to be a wrong launch option specified or no permissions for your user to launch executables where the game is saved. Most likely a wrong launch option.

Can you please try launching the game again? Then, after it fails, scroll down to the footer and click "Send System Report". We'll be able to verify exactly what the problem is :)

**Comment by 3Nex** [comment]
Well actually... I don't know if the file wasn't already executable, I just added that as a guess pretty much... 
Anyway, I sent the system report and I entered this github URL as the description so you know what it refers to.

**Comment by YLivay** [comment]
Thanks for the system report, we'll be looking into it.

**Comment by YLivay** [comment]
Hey are you 32bit or 64bit?

**Comment by CyberKiller40** [comment]
I checked this game - it runs fine from the client for me, though it incorrectly points to the 32bit binary (I checked which file got executable permissions set by the client) even on my 64bit system.

Oh yeah it's also missing fonts, probably the author used some windows specific font and didn't bundle it. Anyway it's the game that needs fixing first.

**Comment by YLivay** [comment]
Yup, getting exactly what @CyberKiller40's getting. It may be this game's launch options because other games do take the 64 bit version properly when set (Down Ward for example).

**Comment by YLivay** [comment]
Yeah the game has only a 32 bit launch option specified.
To get it working you probably need to install the 32 bit versions of the libs it needs.
Try launching the .x86 binary from the terminal and see what it complains about.

Also, would be a good idea to let the developer know, because this is a pretty good lil game (which almost made me cry damnit)
