### ISSUE TITLE
Batch Game won't open!

### ISSUE THREAD

**Issue by zombieknifer223** [gamejolt/issue-tracker#635]
I installed my game with the new pre-released GameJolt client and it made my Batch Game unplayable! The only way to play it is by opening it yourself. Please fix it!

**Comment by hworld** [comment]
Hey, would you be able to link the game here so we can test?

**Comment by zombieknifer223** [comment]
http://gamejolt.com/games/minebatch-free-to-play/121300

**Comment by YLivay** [comment]
It launched completely fine for me. Send a system report when you try to launch it, maybe it'll shed some light on the issue.

**Comment by zombieknifer223** [comment]
https://youtu.be/OM2_uD_RUNM (Unlisted)
The video says it all!

**Comment by YLivay** [comment]
Looks like the issue is with the game. It expects things from the user's environment it shouldn't.
When you open a bat file it gets processed by windows command prompt and depending on minor annoying things you may or may not actually launch the game from the directory you think you're launching it from. Launching with double click makes it with the cwd set to where the batch file is. Other ways ignore the environment variables for the cwd and just do whatever they want when cmd takes over and loads in the user configs. Try putting this in the beginning of your bat launcher: `cd /d %~dp0`.

Maybe in the future we could detect these batch files and launch them differently.
Oh! I'll test it with our new client wrapper, it may just work :)

**Comment by zombieknifer223** [comment]
My BAT to EXE converter **requires** the _CD_ thing to be _**CD %MYFILES%**_ to work! Can it be cd /d %~dp0. %MYFILES% ?

**Comment by zombieknifer223** [comment]
I tested it out and It doesn't work. Help or a tutorial?

**Comment by CyberKiller40** [comment]
If you use some kind of tool to make an exe from your batch script then it's not a batch file.

Anyway, try to launch your exe file with this mini script:
https://www.dropbox.com/s/9jj5fj3x6dx1ayq/run.bat?dl=0 (by me, public domain license)
It cd's correctly to the drive and the directory here the files are located. Change the program name in the script and put it next to your exe file, then point GJ to launch this little script.

**Comment by zombieknifer223** [comment]
It works! Thanks!
