### ISSUE TITLE
Case sensitivity throws off patching in Windows

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#658]
When updating on Windows machines, the patcher might delete files it shouldn't.
This happens because of case insensitivity when a file exists in the new installation by a different casing than on the file system. The patcher will mark the file on the filesystem as "removed by new build" because it couldn't find the exact match for it, which makes the patcher remove it after it finishes extracting. So whats happens is that the patcher removes the file it just extracted, and that file also overwrote the existing file so we end up with no file at all.

**Comment by Tricky1975** [comment]
I wonder. I've configured my client (in order to keep my main drive clean) to my external USB drive. Although I am using a Mac (thus with a unix underground and case sensitive) the device in question was ExFAT formatted in order to use it cross-platform (my own game projects are also on that thing, and I need this compatibility to do my Windows builds as well). 

Does this mean this bug can therefore happen on my mac given the described configuration?

**Comment by YLivay** [comment]
Yup, this does happen on mac too. Made a quick fix, just testing it now.

**Comment by YLivay** [comment]
Ok, this is fixed, but i'll be leaving this issue open since case sensitivity on Mac will not be supported. When updating a game it would have traces of similar named different cased files. At least it won't delete anything it shouldnt anymore!

**Comment by YLivay** [comment]
Closing this, we're not planning on supporting case sensitivity on Mac for the near future.
