### ISSUE TITLE
"Free" label

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#674]
Please consider changing the "free" label on the games thumbnails, so it doesn't collide with the Free Software Foundation's definition of free (libre).

Alternatives:
- Freeware
- Free2Play
- PWYW / Pay What You Want

Additionally it would be nice if GJ had a tag for truly FLOSS games (published under a free license and providing source code). There aren't many of those, but not that few either. It could be named just that - "FLOSS" (naming it "free" would cause too many people to mislabel).

**Comment by hworld** [comment]
Isn't "libre" the new thing they're saying anyway? Maybe we can call it "FREEDOM". haha

I think for the majority of users FREE is pretty clear. Freeware is a possibility, though... I could always do a little twitter survey some time.

**Comment by Tricky1975** [comment]
Cyber has a point. Free software is not always free of charge. When speaking of free software we only means that the license gives you the freedom to do things commercial software does not allow you to. And sometimes free software is included in a paid package in order to make stuff work (like how old DOS games are sold in a DOSBOX wrapper on GOG.COM). 

And free of charge software does not always have a free license either. If I offer a game free of charge but only allow GameJolt to host it, then the open source junkies will complain the term "free" was misleading. (not that I plan to, since I develop open-source and only keep a few security portions close-sourced).

Some people do indeed expect a free (as in freedom) license when searching for "free software", and any form of confusion on this matter can harm Game Jolt's name as true "Free Software Junkies" can be whiners and jerks when it comes to these matters and write some very nasty blogs and stuff about that.

**Comment by CyberKiller40** [comment]
You say as if defending the proper meaning is something bad.

Steam uses the term free to play, that could be shortened to 'F2P'. What the majority thinks isn't necessarily correct.

**Comment by hworld** [comment]
Made a tweet to gather feedback: https://twitter.com/gamejolt/status/730729844376514560

**Comment by CyberKiller40** [comment]
The question in that tweet is wrong. You set the question to get people to get an answer that you like :-P. The correct question should include info why free is not good because it clashes with FLOSS.

Good question: "Do you think calling zero-cost games 'free' is good? Remember that this could be confused with Free/Libre and Open Source Software"

**Comment by YLivay** [comment]
I think we should keep it simple and straightforward. I don't see any reason to be super politically correct on this haha. You'd almost never catch anyone throwing "Play my free to play game" or "This is a cool freeware game". Besides, the labels can be kept short and less annoying in the thumbnail when they aren't a paragraph obscuring the bottom part of the thumbnail.
