### ISSUE TITLE
Improvement: Thumbnail badge for paid games featuring a free demo.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#690]
I myself strongly believe in the "try-before-you-buy" concept. If I would ever put a paid game on GameJolt it is very likely a free demo will come along with it, or that I release my game in the same concept as Wolfenstein 3D did (six playable episodes of which the first one is free, and the other five are paid).

However since only a price is shown, you cannot tell by the thumbnail if there is a free demo or not.
Now I know the price is shown based on the price of the primary build, but this does not fully work in this idea either. I mean, if I make the demo primary and the full game paid the thumbnail badge will say "free" and I think I will get a lot of complaints for "swindling" if people find out the "real game" is paid. 

I do think a demo should be marked as such though. I mean if Dyrt would be a paid game (I got no plans for that, but it will have to do for this hypothesis), you can see that aside from the game itself the game page also features the game's manual, and a free novel of which the story is very heavily connected to the events in the game. It would not be very prudent if any of those two would be picked up as "free demo".

The idea came up in a discussion that came to be in the [official "I am against paid games" thread](gamejolt.com/f/the-official-i-am-against-paid-games-thread/22877) (which I branded as such as a moderator to give opposers a place to whi... I mean complain and to prevent a high-load of complaint threads like we had at the peak of the fnaf-crisis), and I am surprised a good idea would arise in that specific thread ;)

(Also it would be a good idea to make the filters so sophisticated you can search for as well free and paid stuff or stuff that has free content, regardless if paid stuff is there too).

**Comment by hworld** [comment]
Yeah, this is a tricky one. I haven't really been able to find something I like. The problem is the Game Jolt packaging system is very flexible, but it's hard to distill that down to a single thumbnail price. Then again, when browsing, seeing a single price is important. It's too hard to digest a whole packaging structure, I think.

As for people not putting their paid one as primary if it really is the primary, I'm viewing that as going against the terms. I may hide games that don't do that and request them to change it. And, as you say, users will probably be upset which would only hurt their image.

I was considering specific types of packages, such as Demo, Soundtrack, etc. I'm not sure what I think just yet. I think it could be really cool to browse games with demos, though. I'll give it some thought and see how hard it would be.

**Comment by Tricky1975** [comment]
[#gj-improve](https://gamejolt.com/f/improvement-thumbnail-badge-for-paid-games-featuring-a-free-demo/341372?sort=active)
