### ISSUE TITLE
I deleted the client and after installed again i setting my game directory but it wasnt detect the files in there

### ISSUE THREAD

**Issue by DarkCybrid** [gamejolt/issue-tracker#801]
So what should i do, there is a way to detect the lient the files because i had so many game downloaded and now i need to reinstall them and the saves are lost too and dont want this.

**Comment by YLivay** [comment]
The game index is stored in a localdb in a folder that uninstallation shouldn't remove. Did you by chance manually remove a folder called game-jolt-client in your appdata?

**Comment by DarkCybrid** [comment]
Hello i dont really get it but i never had a game-jolt-client folder in my appdata but i have a folder in my external hard drive where i installed the games for the case if i should re-install my windows and i need to recover my games and in this folder have the 'Games' folder and otherthing like cache,database,.. folder and web data,cookies files so and i tried located as i did with the steam games but it doesnt loaded. So i hope i was lear because the english not my main language and if i misunderstand you and still your answer is the solution then you could explain this with more detail.

UI:Sorry for this long answer i just want to be sure i give all information what is important in this case.

**Comment by YLivay** [comment]
A longer answer is excellent, the more info the more we can help :)

When you install a game on Game Jolt it saves where the game is in some other location on your computer so even if you reinstall it - it should've automatically detected the games, you don't have to re-add or point your directory in settings at them. If it didn't find them this may be caused by two things:
1. The local db we saved where the games are installed to is corrupted.
2. The games directory has been moved.

In the first case, there's sadly not much we can do but reinstall the games :(
In the second case, if its possible to move the games back to where they were it'll be detected, but there's currently no support for moving the games around. yet. We might add it in future releases tho
