### ISSUE TITLE
"Translate Comments" button should be more subtle

### ISSUE THREAD

**Issue by niksudan** [gamejolt/issue-tracker#928]
Right now it's the first thing a user sees, regardless of if the majority are English. It makes sense to put it under the respective comment/thread, and making it more subtler.

**Comment by hworld** [comment]
hmmm, suppose so. i copied what airbnb does. also, the way it's done is that it translates every single comment on the page rather than just a single one, so i think having the button at the top kind of makes sense for that. also for game pages where there is a lot of comments to translate, we'd end up using a lot more vertical space. not sure what i think, though

**Comment by hworld** [comment]
i'ms aying no
